spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/GBSB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  security:
    user:
      name: user
      password: 1234

server:
  port: 8080

logging:
  level:
    root: debug