spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trablock?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  security:
    user:
      name: user
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: trablock2022@gmail.com
    password: mdoayaxlsjvbizpc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

# 하위 설정값은 파일(이미지) 저장 경로
file:
  upload-dir: ./image


#logging:
#  level:
#    root: debug
