spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/trablock?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver

  #    하위 datasource 는 cafe24 용
  datasource:
    url: jdbc:mysql://localhost:3306/mmnm3
    username: mmnm3
    password: gbsb2022@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
  security:
    user:
      name: user
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: trablock2022@gmail.com
    password: mdoayaxlsjvbizpc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#server:
#  port: 8080

# 하위 설정값은 파일(이미지) 저장 경로
file:
  upload-dir: ./image

#logging:
#  level:
#    root: debug
