spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/GBSB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  security:
    user:
      name: user
      password: 1234

server:
  port: 8080

#logging:
#  level:
#    root: debug
